/**
 * Scheduler — deterministic, race-condition-free execution engine
 * for multiple (Symbol × Timeframe) pairs.
 *
 * Architecture (Design Decision 4):
 * - Single-threaded event loop (JavaScript is single-threaded by nature)
 * - Mutex serializes all wallet-affecting operations
 * - Candle processing for each pair runs sequentially within a tick
 * - Deterministic iteration order over configured pairs
 *
 * @module trading
 */

import type { PairConfig } from './types.js';
import type { StrategyMarker } from '../strategy/strategy-engine.js';

// ---- Types ----

export interface PairId {
  symbol: string;
  timeframe: string;
}

export function pairIdToString(pair: PairId): string {
  return `${pair.symbol}:${pair.timeframe}`;
}

export function parsePairId(id: string): PairId {
  const colon = id.indexOf(':');
  if (colon === -1) throw new Error(`Invalid pair ID: ${id}`);
  return { symbol: id.substring(0, colon), timeframe: id.substring(colon + 1) };
}

/**
 * A candle that has been confirmed (closed).
 */
export interface ClosedCandle {
  symbol: string;
  timeframe: string;
  timestamp: number;
  open: number;
  high: number;
  low: number;
  close: number;
  volume: number;
}

/**
 * A trading signal generated by strategy execution.
 */
export interface TradeSignal {
  pair: PairId;
  action: 'buy' | 'sell' | 'close';
  quantity: number;
  price: number;
  timestamp: number;
  meta?: Record<string, unknown>;
  /** Strategy engine marker that produced this signal (chaos mode). */
  marker?: StrategyMarker;
  /**
   * Entry price of the position this signal closes, preserved through the
   * scheduler round-trip (B1). Set by the strategy executor at generation
   * time; absent when unknown (PnL feed then fails safe and skips).
   */
  positionEntryPrice?: number;
  /**
   * Fraction of available balance to spend on a buy, preserved through the
   * scheduler round-trip for chaos-originated signals (fixed 0.1 = 10% of
   * equity). Strategy signals omit it — the executor then falls back to the
   * configured positionSizePercent.
   */
  sizeFraction?: number;
}

/** Callback for processing a closed candle. */
export type CandleProcessor = (candle: ClosedCandle) => Promise<TradeSignal[]>;

/** Callback for submitting orders (serialized behind mutex). */
export type OrderSubmitter = (signals: TradeSignal[]) => Promise<void>;

// ---- Simple Mutex ----

/**
 * A simple mutex for serializing async operations.
 */
export class Mutex {
  private locked = false;
  private queue: Array<() => void> = [];

  async acquire(): Promise<void> {
    if (!this.locked) {
      this.locked = true;
      return;
    }
    return new Promise((resolve) => {
      this.queue.push(resolve);
    });
  }

  release(): void {
    if (this.queue.length > 0) {
      const next = this.queue.shift()!;
      next();
    } else {
      this.locked = false;
    }
  }

  /** Execute a critical section exclusively. */
  async runExclusive<T>(fn: () => Promise<T>): Promise<T> {
    await this.acquire();
    try {
      return await fn();
    } finally {
      this.release();
    }
  }
}

// ---- Scheduler ----

export interface SchedulerOptions {
  /** Ordered list of pairs to trade. */
  pairs: PairConfig[];
  /** Callback to process a closed candle and get signals. */
  processCandle: CandleProcessor;
  /** Callback to submit orders (serialized). */
  submitOrders: OrderSubmitter;
  /** Whether the scheduler is paused. */
  paused?: boolean;
}

/**
 * Determinstic scheduler for processing candles across multiple pairs.
 *
 * Features:
 * - Deterministic iteration order (pairs processed in configured order)
 * - Mutex-serialized order submission (no race conditions on wallet)
 * - Pause/resume support
 * - Candle processing and order submission are separate phases
 */
export class Scheduler {
  private readonly pairs: PairConfig[];
  private readonly processCandle: CandleProcessor;
  private readonly submitOrders: OrderSubmitter;
  private readonly mutex: Mutex;
  private _paused: boolean;
  private _running = false;
  private tickCount = 0;
  private totalSignalsGenerated = 0;
  private totalOrdersSubmitted = 0;
  private lastTickTime = 0;

  constructor(options: SchedulerOptions) {
    this.pairs = [...options.pairs];
    this.processCandle = options.processCandle;
    this.submitOrders = options.submitOrders;
    this.mutex = new Mutex();
    this._paused = options.paused ?? false;
  }

  /** Whether the scheduler is currently paused. */
  get paused(): boolean {
    return this._paused;
  }

  /** Whether the scheduler is running. */
  get running(): boolean {
    return this._running;
  }

  /** Statistics from the current run. */
  get stats(): SchedulerStats {
    return {
      tickCount: this.tickCount,
      totalSignalsGenerated: this.totalSignalsGenerated,
      totalOrdersSubmitted: this.totalOrdersSubmitted,
      lastTickTime: this.lastTickTime,
      pairCount: this.pairs.length,
    };
  }

  /**
   * Process a batch of closed candles from all pairs.
   *
   * Phase 1: Process candles for each pair in deterministic order,
   * collecting signals.
   * Phase 2: Submit all collected signals via mutex (serialized).
   *
   * @param candles - Closed candles to process
   * @param signal - Optional AbortSignal to cancel processing
   */
  async tick(candles: ClosedCandle[], signal?: AbortSignal): Promise<void> {
    if (this._paused) return;
    if (signal?.aborted) return;

    this._running = true;
    this.tickCount++;
    this.lastTickTime = Date.now();

    const allSignals: TradeSignal[] = [];

    // Phase 1: Process candles in deterministic order (by pair config order)
    for (const pair of this.pairs) {
      if (signal?.aborted) break;

      const pairCandles = candles.filter(
        (c) => c.symbol === pair.symbol && c.timeframe === pair.timeframe,
      );

      for (const candle of pairCandles) {
        if (signal?.aborted) break;

        try {
          const signals = await this.processCandle(candle);
          allSignals.push(...signals);
        } catch (err) {
          // Log error but continue processing other pairs
          console.error(`[Scheduler] Error processing candle for ${pair.symbol}:${pair.timeframe}`, err);
        }
      }
    }

    if (signal?.aborted) return;

    this.totalSignalsGenerated += allSignals.length;

    // Phase 2: Submit orders behind mutex (serialized, no race conditions)
    if (allSignals.length > 0) {
      await this.mutex.runExclusive(async () => {
        await this.submitOrders(allSignals);
      });
      this.totalOrdersSubmitted += allSignals.length;
    }
  }

  /**
   * Pause the scheduler. In-flight processing completes but
   * tick() will be a no-op until resumed.
   */
  pause(): void {
    this._paused = true;
  }

  /** Resume the scheduler. */
  resume(): void {
    this._paused = false;
  }

  /** Stop the scheduler. */
  stop(): void {
    this._running = false;
    this._paused = true;
  }

  /** Reset stats. */
  resetStats(): void {
    this.tickCount = 0;
    this.totalSignalsGenerated = 0;
    this.totalOrdersSubmitted = 0;
    this.lastTickTime = 0;
  }
}

export interface SchedulerStats {
  tickCount: number;
  totalSignalsGenerated: number;
  totalOrdersSubmitted: number;
  lastTickTime: number;
  pairCount: number;
}
