//@version=6
indicator("B-Xtrender @Puppytherapy", overlay=false)

short_l1 = input.int(5, title="Short - L1")
short_l2 = input.int(20, title="Short - L2")
short_l3 = input.int(15, title="Short - L3")

long_l1 = input.int(20, title="Long - L1")
long_l2 = input.int(15, title="Long - L2")

shortTermXtrender = ta.rsi(ta.ema(close, short_l1) - ta.ema(close, short_l2), short_l3) - 50
longTermXtrender = ta.rsi(ta.ema(close, long_l1), long_l2) - 50

shortXtrenderCol =
     shortTermXtrender > 0 ?
         shortTermXtrender > shortTermXtrender[1] ? color.lime : #228B22 :
         shortTermXtrender > shortTermXtrender[1] ? color.red : #8B0000

plot(
     shortTermXtrender,
     color=color.new(shortXtrenderCol, 50),
     style=plot.style_columns,
     linewidth=1,
     title="B-Xtrender Osc. - Histogram"
)

t3(src, len) =>
    xe1 = ta.ema(src, len)
    xe2 = ta.ema(xe1, len)
    xe3 = ta.ema(xe2, len)
    xe4 = ta.ema(xe3, len)
    xe5 = ta.ema(xe4, len)
    xe6 = ta.ema(xe5, len)

    b = 0.7
    c1 = -b * b * b
    c2 = 3 * b * b + 3 * b * b * b
    c3 = -6 * b * b - 3 * b - 3 * b * b * b
    c4 = 1 + 3 * b + b * b * b + 3 * b * b

    c1 * xe6 + c2 * xe5 + c3 * xe4 + c4 * xe3

maShortTermXtrender = t3(shortTermXtrender, 5)

colShortTermXtrender =
     maShortTermXtrender > maShortTermXtrender[1] ? color.lime : color.red

plot(
     maShortTermXtrender,
     color=color.black,
     style=plot.style_line,
     linewidth=5,
     title="B-Xtrender Shadow"
)

plot(
     maShortTermXtrender,
     color=colShortTermXtrender,
     style=plot.style_line,
     linewidth=3,
     title="B-Xtrender Color"
)

plotshape(
     maShortTermXtrender > maShortTermXtrender[1] and
     maShortTermXtrender[1] < maShortTermXtrender[2] ? maShortTermXtrender : na,
     location=location.absolute,
     style=shape.circle,
     color=color.new(color.lime, 10),
     size=size.tiny
)

plotshape(
     maShortTermXtrender < maShortTermXtrender[1] and
     maShortTermXtrender[1] > maShortTermXtrender[2] ? maShortTermXtrender : na,
     location=location.absolute,
     style=shape.circle,
     color=color.new(color.red, 10),
     size=size.tiny
)

longXtrenderCol =
     longTermXtrender > 0 ?
         longTermXtrender > longTermXtrender[1] ? color.lime : #228B22 :
         longTermXtrender > longTermXtrender[1] ? color.red : #8B0000

macollongXtrenderCol =
     longTermXtrender > longTermXtrender[1] ? color.lime : color.red

plot(
     longTermXtrender,
     color=color.new(longXtrenderCol, 80),
     style=plot.style_histogram,
     linewidth=2,
     title="B-Xtrender Trend - Histogram"
)

plot(
     longTermXtrender,
     color=color.new(color.black, 80),
     style=plot.style_line,
     linewidth=5,
     title="B-Xtrender Trend - Line"
)

plot(
     longTermXtrender,
     color=color.new(macollongXtrenderCol, 80),
     style=plot.style_line,
     linewidth=3,
     title="B-Xtrender Trend - Line"
)
